Repository Open-Science-Community-Saudi-Arabia/OSCSA-en-blog, pull requests merged in 2022-12, with the labels that each got.

#45 fix pr template.md file
  .github/workflows/PULL_REQUEST_TEMPLATE.md
  posts/welcome/index.qmd
Labels: bug

#47 fix/PR-template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug

#50 [8/12/2022]Fixs: PR template updated
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#52 Add .gitpod.yml to enable Gitpod
  .gitpod.yml
Labels: Infrastructure

#56 Fix the file name of the blog post and its title
  posts/Sandy-intro/index.qmd
  posts/Sandy-intro/thumbnail.webp
  posts/outreachy-intro/fct.jpg
  posts/outreachy-intro/index.qmd
  posts/outreachy-intro/outreachy-image.png
  posts/outreachy-intro/richie-image.jpg
  posts/outreachy-intro/sandy-image.svg
Labels: enhancement, blog, size/L, kind/bug

#46 [blog]: How to add blog post to OSCSA blog
  posts/How-to-add-blog-post/PR-template.svg
  posts/How-to-add-blog-post/create_PR.svg
  posts/How-to-add-blog-post/create_fork.png
  posts/How-to-add-blog-post/create_new_file.png
  posts/How-to-add-blog-post/create_new_file1.png
  posts/How-to-add-blog-post/create_new_file2.png
  posts/How-to-add-blog-post/create_new_file3.png
  posts/How-to-add-blog-post/create_pullrequest.svg
  posts/How-to-add-blog-post/index.qmd
  posts/How-to-add-blog-post/new_branch1.png
  posts/How-to-add-blog-post/new_branch3.png
  posts/How-to-add-blog-post/new_branch_new.png
  posts/How-to-add-blog-post/preview-netlify.svg
  posts/How-to-add-blog-post/quarto-logo.jpg
  posts/How-to-add-blog-post/quarto.png
  posts/How-to-add-blog-post/quarto2.png
  posts/How-to-add-blog-post/thumbnail.png
  posts/welcome/index.qmd
Labels: blog, kind/documentation, size/L
