Repository Open-Science-Community-Saudi-Arabia/OSCSA-en-blog, pull requests merged in 2022-10, with the labels that each got.

#11 [12/10/2022]: #8 Continuous Integration and Deployment (CI/CD). Fix Deploy Preview not working
  .github/workflows/publish.yml
Labels: outreachy, CI

#5 Internship wrap-up blog
  posts/Internship wrap-up/index.qmd
Labels: blog

#31 [20/10/2022]: Task 5 - Combine Netlify Deploy Action with Quarto Render Action
  .github/workflows/publish.yml
Labels: CI

#30 [20/10/2022]: Task 5 - Add Quarto-Netlify Plugin
  .gitignore
  _quarto.yml
  netlify.toml
  package.json
Labels: enhancement, Plugin
